from unittest.util import _MAX_LENGTH
from django.db import models

class EspnPassingStats(models.Model):
  player_full_name = models.CharField(max_length=50)
  team_full = models.CharField(max_length=30)
  team_abrv = models.CharField(max_length=3)
  season = models.CharField(max_length=25)
  gp = models.SmallIntegerField()
  cmp = models.SmallIntegerField()
  att = models.SmallIntegerField()
  cmp_percent = models.DecimalField()
  yds = models.SmallIntegerField()
  avg = models.DecimalField()
  yds_g = models.DecimalField()
  lng = models.SmallIntegerField()
  td = models.SmallIntegerField()
  int = models.SmallIntegerField()
  sack = models.SmallIntegerField()
  syl = models.SmallIntegerField()
  rtg = models.DecimalField()
  
class EspnRushingStats(models.Model):
  player_full_name = models.CharField(max_length=50)
  team_full = models.CharField(max_length=30)
  team_abrv = models.CharField(max_length=3)
  season = models.CharField(max_length=25)
  gp = models.SmallIntegerField()
  att = models.SmallIntegerField()
  yds = models.SmallIntegerField()
  avg = models.DecimalField()
  lng = models.SmallIntegerField()
  big = models.SmallIntegerField()
  td = models.SmallIntegerField()
  yds_g = models.DecimalField()
  fum = models.SmallIntegerField()
  lst = models.SmallIntegerField()
  fd = models.SmallIntegerField()
  
class EspnDefenseStats(models.Model):
  player_full_name = models.CharField(max_length=50)
  team_full = models.CharField(max_length=30)
  team_abrv = models.CharField(max_length=3)
  season = models.CharField(max_length=25)
  gp = models.SmallIntegerField()
  solo = models.SmallIntegerField()
  ast = models.SmallIntegerField()
  tot = models.SmallIntegerField()
  sack = models.DecimalField()
  sack_yds = models.SmallIntegerField()
  pd = models.SmallIntegerField()
  int = models.DecimalField()
  yds = models.SmallIntegerField()
  lng = models.SmallIntegerField()
  td = models.SmallIntegerField()
  ff = models.SmallIntegerField()
  fr = models.SmallIntegerField()
  ftd = models.SmallIntegerField()
  kb = models.SmallIntegerField()
  
