# Generated by Django 4.1.2 on 2023-10-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspnDefenseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=4, null=True)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('solo', models.SmallIntegerField()),
                ('ast', models.SmallIntegerField()),
                ('tot', models.SmallIntegerField()),
                ('sack', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sack_yds', models.SmallIntegerField()),
                ('pd', models.SmallIntegerField()),
                ('int', models.SmallIntegerField()),
                ('yds', models.SmallIntegerField()),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('ff', models.SmallIntegerField()),
                ('fr', models.SmallIntegerField()),
                ('ftd', models.SmallIntegerField()),
                ('kb', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'espn_defense_stats',
            },
        ),
        migrations.CreateModel(
            name='EspnPassingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=4, null=True)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('cmp', models.SmallIntegerField()),
                ('att', models.SmallIntegerField()),
                ('cmp_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('int', models.SmallIntegerField()),
                ('sack', models.SmallIntegerField()),
                ('syl', models.SmallIntegerField()),
                ('rtg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'espn_passing_stats',
            },
        ),
        migrations.CreateModel(
            name='EspnReceivingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=4, null=True)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('rec', models.SmallIntegerField()),
                ('tgts', models.SmallIntegerField()),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('big', models.SmallIntegerField()),
                ('fum', models.SmallIntegerField()),
                ('lst', models.SmallIntegerField()),
                ('yac', models.SmallIntegerField()),
                ('fd', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'espn_receiving_stats',
            },
        ),
        migrations.CreateModel(
            name='EspnRushingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=4, null=True)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('car', models.SmallIntegerField()),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('big', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fum', models.SmallIntegerField()),
                ('lst', models.SmallIntegerField()),
                ('fd', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'espn_rushing_stats',
            },
        ),
        migrations.AddConstraint(
            model_name='espnrushingstats',
            constraint=models.UniqueConstraint(fields=('player_full_name', 'pos'), name='espn_rushing_stats unique player constraint'),
        ),
        migrations.AddConstraint(
            model_name='espnreceivingstats',
            constraint=models.UniqueConstraint(fields=('player_full_name', 'pos'), name='espn_receiving_stats unique player constraint'),
        ),
        migrations.AddConstraint(
            model_name='espnpassingstats',
            constraint=models.UniqueConstraint(fields=('player_full_name', 'pos'), name='espn_passing_stats unique player constraint'),
        ),
        migrations.AddConstraint(
            model_name='espndefensestats',
            constraint=models.UniqueConstraint(fields=('player_full_name', 'pos'), name='espn_defense_stats unique player constraint'),
        ),
    ]
