# Generated by Django 4.1.2 on 2022-10-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspnDefenseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('solo', models.SmallIntegerField()),
                ('ast', models.SmallIntegerField()),
                ('tot', models.SmallIntegerField()),
                ('sack', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sack_yds', models.SmallIntegerField()),
                ('pd', models.SmallIntegerField()),
                ('int', models.DecimalField(decimal_places=2, max_digits=4)),
                ('yds', models.SmallIntegerField()),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('ff', models.SmallIntegerField()),
                ('fr', models.SmallIntegerField()),
                ('ftd', models.SmallIntegerField()),
                ('kb', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EspnPassingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('cmp', models.SmallIntegerField()),
                ('att', models.SmallIntegerField()),
                ('cmp_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('int', models.SmallIntegerField()),
                ('sack', models.SmallIntegerField()),
                ('syl', models.SmallIntegerField()),
                ('rtg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EspnRushingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('att', models.SmallIntegerField()),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('big', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fum', models.SmallIntegerField()),
                ('lst', models.SmallIntegerField()),
                ('fd', models.SmallIntegerField()),
            ],
        ),
    ]
