# Generated by Django 4.1.2 on 2022-10-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espn_webscrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='espndefensestats',
            table='espn_defense_stats',
        ),
        migrations.AlterModelTable(
            name='espnpassingstats',
            table='espn_passing_stats',
        ),
        migrations.AlterModelTable(
            name='espnrushingstats',
            table='espn_rushing_stats',
        ),
    ]
