# Generated by Django 4.1.2 on 2022-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn_webscrape', '0002_alter_espndefensestats_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspnReceivingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_full_name', models.CharField(max_length=50)),
                ('team_full', models.CharField(max_length=30)),
                ('team_abrv', models.CharField(max_length=3)),
                ('season', models.CharField(max_length=25)),
                ('gp', models.SmallIntegerField()),
                ('rec', models.SmallIntegerField()),
                ('tgts', models.SmallIntegerField()),
                ('yds', models.SmallIntegerField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yds_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.SmallIntegerField()),
                ('td', models.SmallIntegerField()),
                ('big', models.SmallIntegerField()),
                ('fum', models.SmallIntegerField()),
                ('lst', models.SmallIntegerField()),
                ('yac', models.SmallIntegerField()),
                ('fd', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'espn_receiving_stats',
            },
        ),
    ]
