# Generated by Django 4.1.2 on 2023-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn_webscrape', '0002_remove_espndefensestats_espn_defense_stats unique player constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espndefensestats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='espnpassingstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='espnreceivingstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='espnrushingstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
