# Generated by Django 4.1.2 on 2022-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn_webscrape', '0002_espndefensestats_pos_espnpassingstats_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espndefensestats',
            name='int',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='espndefensestats',
            name='sack',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
