version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_nfl_webscrape_web
    # '/start' is the shell script used to run the service
    command: /start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.envs/.env.dev
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_nfl_webscrape_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.envs/.env.dev
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_nfl_webscrape_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - ./.envs/.env.dev
    depends_on:
      - redis
