services:
  - type: worker
    name: celery
    region: oregon
    plan: starter
    env: python
    buildCommand: "pip install -r ./requirements/production.txt"
    startCommand: "./compose/production/django/celery/worker/start.sh"
    autoDeploy: false
  - type: worker
    name: celery-beat
    region: oregon
    plan: starter
    env: python
    buildCommand: "pip install -r ./requirements/production.txt"
    startCommand: "./compose/production/django/celery/beat/start.sh"
    autoDeploy: false
