services:
  - type: web
    name: pro-football-metrics
    region: ohio
    plan: free
    runtime: python
    buildCommand: "./compose/production/django/build.sh"
    startCommand: "gunicorn django_nfl_webscrape.wsgi:application"
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
  - type: worker
    name: celery
    region: ohio
    plan: free
    env: python
    buildCommand: "pip install -r ./requirements/base.txt"
    startCommand: "./compose/production/django/celery/worker/start.sh"
    autoDeploy: false
  - type: cron
    name: celery-beat
    region: ohio
    plan: starter
    env: python
    schedule: "*/30 * * * *"
    buildCommand: "pip install -r ./requirements/base.txt"
    startCommand: "./compose/production/django/celery/beat/start.sh"
    autoDeploy: false

