services:
  - type: worker
    name: celery
    region: ohio
    plan: starter
    env: python
    buildCommand: "pip install -r ./requirements/production.txt"
    startCommand: "celery -A django_nfl_webscrape worker -l INFO --concurrency 1 -E"
    autoDeploy: false
  - type: worker
    name: celery-beat
    region: ohio
    plan: starter
    env: python
    buildCommand: "pip install -r ./requirements/production.txt"
    startCommand: "celery -A django_nfl_webscrape beat -l INFO"
    autoDeploy: false

